# Importin the modules...
# importando los modulos...
import tkinter as tk
import customtkinter as ctk

# setting Dark mode for the form...
# Configurando el modo oscuro para el formulario...
ctk.set_appearance_mode("dark")

# creating the main class for the form or program...
# creando la clase principal para el formulario o programa...
class App(ctk.CTk):
    def __init__(self):
        super().__init__()

        # Creating needed variables for screen width and screen height
        # Variables necesarias para las medidas de la ventana
        global width, height, medium_width, medium_height
        width, height = self.winfo_screenwidth(), self.winfo_screenheight()
        medium_width = int(width/2)
        medium_height = int(height/2)

        # Creating a minimal app...
        # Creando una app minima...
        self.geometry(f"{medium_width}x{height}+560+0") # Change this | Cambia esto...

        # Call the widgets funtion...
        # llama la función de los widgets...
        self.createWidgets()


    # Validating and processing the data...
    # Validando y procesando los datos...
    def validate(self):
        username = self.username_entry.get()
        password = self.password_entry.get()

        # The logic... La lógica
        if(username == "steve" and password == "123"):
            self.validate_text.configure(text=f"Welcome to the system, {username}", fg="lime")
        else:
            self.validate_text.configure(text=f"Incorrect Data, try again!",
                                         fg="red",
                                         bg="#000000")

        # Create a function for placing the widgets in the window...
        # crea una función para ubicar los widgets o elementos en la ventana...
    def createWidgets(self):
        
       
        # Create a Canvas with tkinter...
        # crea un lienzo(canvas) con tkinter
        self.canvas =  tk.Canvas(self, width=width, height=height, background="#000000")
        self.canvas.grid()

        # Create a username entry...
        # Crea una entrada para el nombre de usuario...
        self.username_entry = ctk.CTkEntry(self.canvas, border_color="#802626",
                                        fg_color="black", bg_color="#000000",
                                        placeholder_text="Enter your username...",
                                        placeholder_text_color="gray32")

        # Create a password entry too...
        # Crea una entrada para contraseña también...
        self.password_entry = ctk.CTkEntry(self.canvas, border_color="#802626",
                                        fg_color="black", bg_color="#000000",
                                        placeholder_text="Enter your password...",
                                        placeholder_text_color="gray32")

        # Create a login button...
        # Crea un botón de loguin...
        self.login_button = ctk.CTkButton(self.canvas, text="Login", bg_color="#000000",
                                          fg_color="#802626",
                                          text_color="white", hover_color=("white", "#26805e"),
                                          cursor="hand2", 
                                          command=self.validate)
    
        # Create a text for validating data...
        # Crea un texto para validar los datos...
        self.validate_text = tk.Label(self.canvas, fg="yellow", bg="#000000")



        # Create a title...
        # Crea un titulo...
        # Center the text... | centra el texto si deseas, I want it to the left | lo dejaré a la izquierda
        self.canvas.create_text(((medium_width)/2)-150, ((medium_height)/2)-100, text="Login Form", fill="#26805e",
                                font=("Arial", 24, "italic"))
        

        # text for username...
        # texto para describir el nombre de usuario...
        self.canvas.create_text(((medium_width)/2), ((medium_height)/2)-40, text="Username", fill="#26805e",
                                font=("Arial", 16, "italic"))

        # Placing the entry into the canvas...
        # Ubica el entry en el canvas...
        self.canvas.create_window((medium_width)/2, (medium_height)/2, window=self.username_entry)

        # text for password...
        # texto para la contraseña...
        self.canvas.create_text(((medium_width)/2), ((medium_height)/2)+100, text="Password", fill="#26805e",
                                font=("Arial", 16, "italic"))

        # Placing the password entry...
        # Ubica la entrada de contraseña...
        self.canvas.create_window((medium_width)/2, ((medium_height)/2)+140, window=self.password_entry)

        # Placing the button in canvas...
        # Ubica el botón en el lienzo...
        self.canvas.create_window((medium_width)/2, ((medium_height)/2)+180, window=self.login_button)

        self.canvas.create_window((medium_width)/2, ((medium_height)/2)+240, window=self.validate_text)

app = App()
app.mainloop()